services:
  kafka-broker:
    extends:
      file: docker-compose-base.yaml
      service: kafka-broker
  generator:
    extends:
      file: docker-compose-base.yaml
      service: generator
    command: [ "python", "-m", "db_generate" ]
    environment:
      - DB_HOST=postgres
      - DB_NAME=stream
    scale: 1
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    build: ./services/postgres
    shm_size: 100mb
    restart: always
    networks:
      datapipe_net:
    scale: 1
    ports:
      - "5432:5432"
    environment:
      - RUNTIME_ENV=docker
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - POSTGRES_DB=stream
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - REPLICATION_PASSWORD=replication_password
      - REPLICATION_SLOT_NAME=cdc_slot
      - PUBLICATION_NAME=cdc
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./services/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    command: [ "-c", "config_file=postgresql.conf" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "stream" ]
      interval: 1s
      timeout: 5s
      retries: 10
networks:
  datapipe_net:
