version: '3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  kafka-broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - mqtt-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./kafka.properties:/etc/kafka/kafka.properties

  kafka-mqtt-bridge:
    image: confluentinc/cp-kafka-mqtt:latest
    depends_on:
      - mqtt-broker
      - kafka-broker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      MQTT_BROKER: mqtt-broker:1883
      MQTT_TOPIC: iot-data

  flink:
    image: flink:latest
    depends_on:
      - kafka-broker
    ports:
      - "8081:8081"
    environment:
      FLINK_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      FLINK_KAFKA_TOPIC: iot-data
    volumes:
      - ./flink.properties:/etc/flink/flink.properties

  sveltekit:
    image: node:latest
    depends_on:
      - flink
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./sveltekit-app:/app
    command: npm run dev

  iot-message-generator:
    image: python:latest
    depends_on:
      - mqtt-broker
    volumes:
      - ./iot-message-generator.py:/app/iot-message-generator.py
    command: python /app/iot-message-generator.py