services:
  notebook:
    extends:
      file: docker-compose-base.yaml
      service: notebook
  kafka-broker:
    extends:
      file: docker-compose-base.yaml
      service: kafka-broker
  risingwave:
    extends:
      file: docker-compose-rw.yaml
      service: risingwave
  generator:
    extends:
      file: docker-compose-base.yaml
      service: generator
    command: [ "python", "-m", "generator", "--topic", "message" ]
    scale: 3
  ml:
    build: ./services/ml
    ports:
      - "8000:8000"
    networks:
      datapipe_net:
    command: [ "faststream", "run", "src/stream:app" ]
    depends_on:
      generator:
        condition: service_started
    environment:
      - MODEL_DIR=/app/models
      - KAFKA_CONSUMER_TOPIC=message
      - KAFKA_PRODUCER_TOPIC=message_emotions
      - BOOTSTRAP_SERVERS=kafka-broker:9092
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./services/ml/src/:/app/src
networks:
  datapipe_net:
