services:
  notebook:
    extends:
      file: docker-compose-base.yaml
      service: notebook
    networks:
      datapipe_net:
  kafka-broker:
    extends:
      file: docker-compose-base.yaml
      service: kafka-broker
    networks:
      datapipe_net:
  generator:
    build:
      context: services/kafka
      dockerfile: Dockerfile
    depends_on:
      kafka-broker:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka-broker:9092
    networks:
      datapipe_net:
    ports:
      - 1111-2222:8000
    volumes:
      - ./services/kafka/src/:/home/app/
    command: [ "python", "-m", "generator", "--topic", "message" ]
    scale: 2
  risingwave:
    image: risingwavelabs/risingwave
    container_name: risingwave
    networks:
      datapipe_net:
    ports:
      - 4566:4566
      - 5691:5691
    command: single_node
    scale: 1
    environment:
      - RUNTIME_ENV=docker
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
networks:
  datapipe_net:
