[project]
name = "generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "avro>=1.12.0",
    "faker>=37.0.0",
    "kafka-python>=2.0.6",
    "psycopg>=3.2.6",
    "psycopg-binary>=3.2.6",
]
