blob:
  server:
    port: '6124'
fs:
  s3a:
    access:
      key: admin
    impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    aws:
      credentials:
        provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    secret:
      key: password
    path:
      style:
        access: true
    connection:
      ssl:
        enabled: false
    endpoint: http://minio:9000
  allowed-fallback-filesystems: s3,s3a
jobmanager:
  rpc:
    address: flink-jobmanager
    port: 6123
  memory:
    process:
      size: 1024m
state:
  savepoints:
    dir: file:///opt/flink/savepoints
  backend: filesystem
  checkpoints:
    dir: file:///opt/flink/checkpoints
heartbeat:
  interval: '1000'
  timeout: '5000'
query:
  server:
    port: '6125'
taskmanager:
  numberOfTaskSlots: 2
  memory:
    process:
      size: 1024m
log:
  level: INFO
  file: /opt/flink/log/flink.log
execution:
  checkpointing:
    interval: 10000
    timeout: 600000
    min-pause: 5000
    max-concurrent-checkpoints: 1
restart-strategy: fixed-delay
