# .github/workflows/check-cdc.yaml
name: CDC Docker Compose

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docker-compose-cdc.yaml'
      - 'services/postgres/**/*'
      - 'services/sequin/**/*'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docker-compose-cdc.yaml'
      - 'services/postgres/**/*'
      - 'services/sequin/**/*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download test data
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Validate CDC workflow
        run: |
          docker compose -f docker-compose-cdc.yaml config
          docker compose -f docker-compose-cdc.yaml up -d
          # Wait for services to be ready
          sleep 10
          # Check sequin service is up
          docker ps | grep sequin
          # Check postgres is up
          docker ps | grep postgres
          # Verify postgres is accessible
          docker exec postgres pg_isready -h localhost -p 5432
          docker compose -f docker-compose-cdc.yaml down